+ cd lib
+ ./Allwmake
+ wmake libso
wmakeLnInclude: linking include files to ./lnInclude
Making dependency list for source file pemfcSpecie/pemfcSpecie.C
Making dependency list for source file regionProperties/regionProperties.C
Making dependency list for source file polyToddYoung/polyToddYoung.C
Making dependency list for source file diffusivityModels/porousFSG/porousFSG.C
Making dependency list for source file diffusivityModels/binaryFSG/binaryFSG.C
Making dependency list for source file diffusivityModels/fsgMolecularWeights/fsgMolecularWeights.C
Making dependency list for source file diffusivityModels/fsgDiffusionVolumes/fsgDiffusionVolumes.C
Making dependency list for source file diffusivityModels/knudsen/knudsen.C
Making dependency list for source file diffusivityModels/fixedDiffusivity/fixedDiffusivity.C
Making dependency list for source file diffusivityModels/diffusivityModel/newDiffusivityModel.C
Making dependency list for source file diffusivityModels/diffusivityModel/diffusivityModel.C
Making dependency list for source file myPorosityModel/myPowerLaw/myPowerLaw.C
Making dependency list for source file myPorosityModel/myFixedCoeff/myFixedCoeff.C
Making dependency list for source file myPorosityModel/myDarcyForchheimer/myDarcyForchheimer.C
Making dependency list for source file myPorosityModel/myPorosityModel/myIOporosityModelList.C
Making dependency list for source file myPorosityModel/myPorosityModel/myPorosityModelList.C
Making dependency list for source file myPorosityModel/myPorosityModel/myPorosityModelNew.C
Making dependency list for source file myPorosityModel/myPorosityModel/myPorosityModel.C
Making dependency list for source file myPatchToPatchInterpolation/myPatchToPatchInterpolationName.C
Making dependency list for source file smearPatchToMesh/smearPatchToMesh.C
Making dependency list for source file smearPatchToMesh/regionInfo.C
Making dependency list for source file myMeshWave/myFaceCellWaveName.C
Making dependency list for source file myMeshWave/myMeshWaveName.C
Making dependency list for source file myContinuityErrs/myContinuityErrs.C
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myContinuityErrs/myContinuityErrs.C -o Make/linux64GccDPInt32Opt/myContinuityErrs/myContinuityErrs.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myMeshWave/myMeshWaveName.C -o Make/linux64GccDPInt32Opt/myMeshWave/myMeshWaveName.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myMeshWave/myFaceCellWaveName.C -o Make/linux64GccDPInt32Opt/myMeshWave/myFaceCellWaveName.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c smearPatchToMesh/regionInfo.C -o Make/linux64GccDPInt32Opt/smearPatchToMesh/regionInfo.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c smearPatchToMesh/smearPatchToMesh.C -o Make/linux64GccDPInt32Opt/smearPatchToMesh/smearPatchToMesh.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myPatchToPatchInterpolation/myPatchToPatchInterpolationName.C -o Make/linux64GccDPInt32Opt/myPatchToPatchInterpolation/myPatchToPatchInterpolationName.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myPorosityModel/myPorosityModel/myPorosityModel.C -o Make/linux64GccDPInt32Opt/myPorosityModel/myPorosityModel/myPorosityModel.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myPorosityModel/myPorosityModel/myPorosityModelNew.C -o Make/linux64GccDPInt32Opt/myPorosityModel/myPorosityModel/myPorosityModelNew.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myPorosityModel/myPorosityModel/myPorosityModelList.C -o Make/linux64GccDPInt32Opt/myPorosityModel/myPorosityModel/myPorosityModelList.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myPorosityModel/myPorosityModel/myIOporosityModelList.C -o Make/linux64GccDPInt32Opt/myPorosityModel/myPorosityModel/myIOporosityModelList.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myPorosityModel/myDarcyForchheimer/myDarcyForchheimer.C -o Make/linux64GccDPInt32Opt/myPorosityModel/myDarcyForchheimer/myDarcyForchheimer.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myPorosityModel/myFixedCoeff/myFixedCoeff.C -o Make/linux64GccDPInt32Opt/myPorosityModel/myFixedCoeff/myFixedCoeff.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c myPorosityModel/myPowerLaw/myPowerLaw.C -o Make/linux64GccDPInt32Opt/myPorosityModel/myPowerLaw/myPowerLaw.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c diffusivityModels/diffusivityModel/diffusivityModel.C -o Make/linux64GccDPInt32Opt/diffusivityModels/diffusivityModel/diffusivityModel.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c diffusivityModels/diffusivityModel/newDiffusivityModel.C -o Make/linux64GccDPInt32Opt/diffusivityModels/diffusivityModel/newDiffusivityModel.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c diffusivityModels/fixedDiffusivity/fixedDiffusivity.C -o Make/linux64GccDPInt32Opt/diffusivityModels/fixedDiffusivity/fixedDiffusivity.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c diffusivityModels/knudsen/knudsen.C -o Make/linux64GccDPInt32Opt/diffusivityModels/knudsen/knudsen.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c diffusivityModels/fsgDiffusionVolumes/fsgDiffusionVolumes.C -o Make/linux64GccDPInt32Opt/diffusivityModels/fsgDiffusionVolumes/fsgDiffusionVolumes.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c diffusivityModels/fsgMolecularWeights/fsgMolecularWeights.C -o Make/linux64GccDPInt32Opt/diffusivityModels/fsgMolecularWeights/fsgMolecularWeights.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c diffusivityModels/binaryFSG/binaryFSG.C -o Make/linux64GccDPInt32Opt/diffusivityModels/binaryFSG/binaryFSG.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c diffusivityModels/porousFSG/porousFSG.C -o Make/linux64GccDPInt32Opt/diffusivityModels/porousFSG/porousFSG.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c polyToddYoung/polyToddYoung.C -o Make/linux64GccDPInt32Opt/polyToddYoung/polyToddYoung.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c regionProperties/regionProperties.C -o Make/linux64GccDPInt32Opt/regionProperties/regionProperties.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c pemfcSpecie/pemfcSpecie.C -o Make/linux64GccDPInt32Opt/pemfcSpecie/pemfcSpecie.o
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/myContinuityErrs/myContinuityErrs.o Make/linux64GccDPInt32Opt/myMeshWave/myMeshWaveName.o Make/linux64GccDPInt32Opt/myMeshWave/myFaceCellWaveName.o Make/linux64GccDPInt32Opt/smearPatchToMesh/regionInfo.o Make/linux64GccDPInt32Opt/smearPatchToMesh/smearPatchToMesh.o Make/linux64GccDPInt32Opt/myPatchToPatchInterpolation/myPatchToPatchInterpolationName.o Make/linux64GccDPInt32Opt/myPorosityModel/myPorosityModel/myPorosityModel.o Make/linux64GccDPInt32Opt/myPorosityModel/myPorosityModel/myPorosityModelNew.o Make/linux64GccDPInt32Opt/myPorosityModel/myPorosityModel/myPorosityModelList.o Make/linux64GccDPInt32Opt/myPorosityModel/myPorosityModel/myIOporosityModelList.o Make/linux64GccDPInt32Opt/myPorosityModel/myDarcyForchheimer/myDarcyForchheimer.o Make/linux64GccDPInt32Opt/myPorosityModel/myFixedCoeff/myFixedCoeff.o Make/linux64GccDPInt32Opt/myPorosityModel/myPowerLaw/myPowerLaw.o Make/linux64GccDPInt32Opt/diffusivityModels/diffusivityModel/diffusivityModel.o Make/linux64GccDPInt32Opt/diffusivityModels/diffusivityModel/newDiffusivityModel.o Make/linux64GccDPInt32Opt/diffusivityModels/fixedDiffusivity/fixedDiffusivity.o Make/linux64GccDPInt32Opt/diffusivityModels/knudsen/knudsen.o Make/linux64GccDPInt32Opt/diffusivityModels/fsgDiffusionVolumes/fsgDiffusionVolumes.o Make/linux64GccDPInt32Opt/diffusivityModels/fsgMolecularWeights/fsgMolecularWeights.o Make/linux64GccDPInt32Opt/diffusivityModels/binaryFSG/binaryFSG.o Make/linux64GccDPInt32Opt/diffusivityModels/porousFSG/porousFSG.o Make/linux64GccDPInt32Opt/polyToddYoung/polyToddYoung.o Make/linux64GccDPInt32Opt/regionProperties/regionProperties.o Make/linux64GccDPInt32Opt/pemfcSpecie/pemfcSpecie.o -L/home/fatima/OpenFOAM/OpenFOAM-4.0/platforms/linux64GccDPInt32Opt/lib \
    -lfiniteVolume -lmeshTools  -o /home/fatima/OpenFOAM/fatima-4.0/platforms/linux64GccDPInt32Opt/lib/libSinglephasePEMFC.so
'/home/fatima/OpenFOAM/fatima-4.0/platforms/linux64GccDPInt32Opt/lib/libSinglephasePEMFC.so' is up to date.
+ pwd
/home/fatima/OpenFOAM/fatima-4.0/run/pemfcSinglePhaseModel-4.0/pemfcSinglePhaseNonIsothermalSolver
+ cd applications
+ wmake
Making dependency list for source file pemfcSinglephaseNonIsothermalSolver.C
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I../src/constants -I../src/createFields -I../src/createMesh -I../src/createSpecies -I../src/diffusivity -I../src/electrochemistry -I../src/energyTransport -I../src/mapping -I../src/momentumTransport -I../src/multiSpeciesTransport -I../src/patch -I../src/physicalProperties -I../src/readParameters -I../src/readProperties -I../src/tools/functions -I../src/tools/functionIntegration -I../src/tools/ReynoldsNumber -I../src/tools/RiddersRoot -I../src/tools/varInit -I../lib/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/thermophysicalModels/specie/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -c pemfcSinglephaseNonIsothermalSolver.C -o Make/linux64GccDPInt32Opt/pemfcSinglephaseNonIsothermalSolver.o
pemfcSinglephaseNonIsothermalSolver.C: In function ‘int main(int, char**)’:
pemfcSinglephaseNonIsothermalSolver.C:60:5: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
 int main(int argc, char *argv[])
     ^
g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -g -I../src/constants -I../src/createFields -I../src/createMesh -I../src/createSpecies -I../src/diffusivity -I../src/electrochemistry -I../src/energyTransport -I../src/mapping -I../src/momentumTransport -I../src/multiSpeciesTransport -I../src/patch -I../src/physicalProperties -I../src/readParameters -I../src/readProperties -I../src/tools/functions -I../src/tools/functionIntegration -I../src/tools/ReynoldsNumber -I../src/tools/RiddersRoot -I../src/tools/varInit -I../lib/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/finiteVolume/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/meshTools/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/thermophysicalModels/specie/lnInclude  -IlnInclude -I. -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OpenFOAM/lnInclude -I/home/fatima/OpenFOAM/OpenFOAM-4.0/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/pemfcSinglephaseNonIsothermalSolver.o -L/home/fatima/OpenFOAM/OpenFOAM-4.0/platforms/linux64GccDPInt32Opt/lib \
    -L/home/fatima/OpenFOAM/fatima-4.0/platforms/linux64GccDPInt32Opt/lib -lfiniteVolume -lmeshTools -lspecie -lSinglephasePEMFC -lOpenFOAM -ldl  \
     -lm -o /home/fatima/OpenFOAM/fatima-4.0/platforms/linux64GccDPInt32Opt/bin/pemfcSinglephaseNonIsothermalSolver
